name: Docker build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: genschsa
  REPO_NAME: ${{ github.event.repository.name }}

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up environment
        run: |
          APP_VERSION=$(jq -r .version package.json)
          APP_VERSION_MAJOR=$(jq -r '.version | split(".")[0]' package.json)
          APP_VERSION_MINOR=$(jq -r '.version | split(".")[1]' package.json)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "APP_VERSION_MAJOR=$APP_VERSION_MAJOR" >> $GITHUB_ENV
          echo "APP_VERSION_MINOR=$APP_VERSION_MINOR" >> $GITHUB_ENV
          echo "VERSION_TAG=$APP_VERSION-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "IMAGE_REPOSITORY=$REGISTRY/$DOCKERHUB_USERNAME/$REPO_NAME" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Login to Docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest
            type=raw,value=${{ env.APP_VERSION }}
            type=raw,value=${{ env.APP_VERSION_MAJOR}}.${{ env.APP_VERSION_MINOR}}
            type=raw,value=${{ env.APP_VERSION_MAJOR}}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6
